ModifyHow = function(){}
ModifyHow.DELETE = 'DELETE';
ModifyHow.REPLACE = 'REPLACE';
ModifyHow.INSERT = 'INSERT';
ModifyHow.INSERT_AFTER = 'INSERT_AFTER';
ModifyHow.ANNOTATE = 'ANNOTATE';
ModifyHow.CLEAR_ANNOTATION = 'CLEAR_ANNOTATION';
ModifyHow.UPDATE_ELEMENT = 'UPDATE_ELEMENT';